collections:
  categories:
    output: true
    permalink: /category/:name
  tags:
    output: true
    permalink: /tag/:name

#sidebar names
sidebar:
  home:              home
  about:             about
  articles:          articles

#navbar names
navbar:
  jian:              简
  jianshu:           简书
  
# Permalinks
permalink:           pretty

# Conversion
markdown:    kramdown
highlighter: rouge
excerpt_separator: "\n\n\n"

# Setup
title:               example
name:                bigablecat
namecn:              example
tagline:             "'s blog"
description:         "example's blog"
url:                 "http://example.github.io"
baseurl:             ''

autopages:
  enabled: true
  tags:
    layouts: 
      - category_or_tag.html
    enabled: true
  categories:
    layouts:
      - category_or_tag.html
    enabled: true
  collections:
    enabled: false

# Pagination Settings
pagination:
  enabled: true
  per_page: 1
  permalink: '/page:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2


gems:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-seo-tag

# About/contact
author:
  name:              example
  url:               "http://example.github.io"
  email:             "example@example.com"

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: categories
    values:
      layout: category_or_tag
  
  -
    scope:
      path: ""
      type: tags
    values:
      layout: category_or_tag
    
# Custom vars
version:             1.0.0
